// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_xbwYW-pnHP-bu4YA7aSBaFffQM4C_4',
    appId: '1:589894780984:web:33b60662e64d7d52c8becd',
    messagingSenderId: '589894780984',
    projectId: 'getrightmeal-2599e',
    authDomain: 'getrightmeal-2599e.firebaseapp.com',
    storageBucket: 'getrightmeal-2599e.firebasestorage.app',
    measurementId: 'G-Y2VP3JFQS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsWKtXOukjz4odMoqGea5fPccXeWZtKs8',
    appId: '1:589894780984:android:b0abf0e42c1be50dc8becd',
    messagingSenderId: '589894780984',
    projectId: 'getrightmeal-2599e',
    storageBucket: 'getrightmeal-2599e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlvfrcNVhLsgH6h5LkH8mHojFuubNdXdw',
    appId: '1:589894780984:ios:8d5fe6eb51f33306c8becd',
    messagingSenderId: '589894780984',
    projectId: 'getrightmeal-2599e',
    storageBucket: 'getrightmeal-2599e.firebasestorage.app',
    iosBundleId: 'com.getrightmealnew.getrightmealnew',
  );
}
